import { GetServerSideProps } from 'next'
import useAuth, { User } from '@/contexts/AuthContext'
import { parseCookies } from "nookies"
import { getApi } from '@/services/getApi'

import Head from 'next/head'
import { Course } from '@/types'
import { Box, Flex } from '@chakra-ui/react'
import { Header } from '../interface'

interface Props {
  user: User
  courses: Course[]
}

export default function Home({ user, courses }: Props) {

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="logo/favicon.ico" />
      </Head>

      <>
        <Header/>
        <Flex pos="relative" >
          <Box 
            w="100%" 
            h="100vh" 
            bgImage="url('main-wallpaper.png')" bgPos="center" bgSize="cover"
          >

          </Box>
          <Box 
            top="0" 
            left="0" 
            w="100%" 
            h="100%"
            pos="absolute"
            bgImage="linear-gradient(to bottom, transparent, #141414  )" 
          />
        </Flex>
        <Box 
          h="100vh" 
          w="100%" 
          bg="#141414"
        >

        </Box>
      </>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  
  const { ["session"]: token } = parseCookies(context)
  const api = getApi(context)

  if (!token) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false
      },
    }
  }

  const userResponse = await api.get("/user")
  const dataResponse = await api.get<Course>("/courses")
  const { user }: { user: User }  = userResponse.data
  
  return {
    props: {
      user,
      courses: dataResponse.data
    },
  }
}