import { Box, Button, Center, Container, Flex, Input, Stack } from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import { parseCookies } from 'nookies'

import useAuth from '@/contexts/AuthContext'
import Head from 'next/head'
import { AuthPanel } from '../interface'

export default function Login() {

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="logo/favicon.ico" />
      </Head>

      <Flex 
        h="100vh" 
        flexDir={["column", "column", "row"]}
      >
        <Box 
          w="100%" 
          bgPos="center"
          bgSize="cover"
          h={["20%", "20%", "100%" ]}
          bgImage="url('main-wallpaper.png')"
        />
        
        <Box 
          w="100%" 
          bg="dark.100"
          bgSize="cover"
          h={["80%", "80%", "100%"]}
        >
          <AuthPanel/>      
        </Box>
      </Flex>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  
  const { ["session"]: token } = parseCookies(context)
  
  if (token) {
    return {
      redirect: {
        destination: "/",
        permanent: false
      },
    }
  }
  
  return {
    props: {},
  }
}